### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by martenring** [MrDando/Weather-App#2]
It is a very good script!! But, I do not any idea how install this script. Can you please explain me?

**Comment by stanic-danijel** [comment]
Hey martenring.

This is just a portfolio project created for [The Odin Project](https://www.theodinproject.com/) course where I am currently learning web development. As such there is nothing to install here.

If you are creating your own weather application you can check the APIs that I used in the app as they could prove useful to you (they are listed in README), but besides that this is really just a school project.

Good luck and happy coding.
